### ISSUE TITLE
Causes Angular builds to fail: node_modules/ng2-uuid/index.ts is missing from the TypeScript compilation

### ISSUE THREAD

**Issue by rjsteinert** [wulfsolter/angular2-uuid#13]
```

ERROR in ./node_modules/ng2-uuid/index.ts
Module build failed: Error: /Users/rjsteinert/Desktop/tangerine-client/node_modules/ng2-uuid/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/rjsteinert/Desktop/tangerine-client/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:709:23)
    at plugin.done.then (/Users/rjsteinert/Desktop/tangerine-client/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Comment by wulfsolter** [comment]
`ng2-uuid`?

**Comment by yankycranky** [comment]
yes please fix this, got the same issue. 
below fix is required in tsconfig.json
  "files": ["index.d.ts"],
